using Ae.Dns.Protocol.Records;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Ae.Dns.Protocol
{
    /// <summary>
    /// Represents an answer to a DNS query, generated by a DNS server.
    /// </summary>
    public sealed class DnsAnswer : IEquatable<DnsAnswer>, IDnsByteArrayReader, IDnsByteArrayWriter
    {
        /// <summary>
        /// The <see cref="DnsHeader"/> section of this answer.
        /// </summary>
        public DnsHeader Header { get; set; } = new DnsHeader();

        /// <summary>
        /// The list of DNS resources returned by the server.
        /// </summary>
        public IList<DnsResourceRecord> Answers { get; set; } = new List<DnsResourceRecord>();

        /// <inheritdoc/>
        public bool Equals(DnsAnswer other) => Header.Equals(other.Header) && Answers.SequenceEqual(other.Answers);

        /// <inheritdoc/>
        public override bool Equals(object obj) => obj is DnsAnswer record ? Equals(record) : base.Equals(obj);

        /// <inheritdoc/>
        public override int GetHashCode() => HashCode.Combine(Header, Answers);

        /// <inheritdoc/>
        public void ReadBytes(byte[] bytes, ref int offset)
        {
            Header.ReadBytes(bytes, ref offset);

            var records = new List<DnsResourceRecord>();
            for (var i = 0; i < Header.AnswerRecordCount + Header.NameServerRecordCount; i++)
            {
                records.Add(bytes.FromBytes<DnsResourceRecord>(ref offset));
            }
            Answers = records.ToArray();
        }

        /// <inheritdoc/>
        public override string ToString() => $"RESPONSE: {Header}";

        /// <inheritdoc/>
        public IEnumerable<IEnumerable<byte>> WriteBytes()
        {
            yield return Header.ToBytes();
            yield return Answers.Select(x => x.ToBytes()).SelectMany(x => x);
        }
    }
}
