name: Deploy

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
      
    - name: Build Estbot
      run: dotnet publish misc/Ae.Dns.Console/Ae.Dns.Console.csproj --configuration Release --runtime linux-arm64 --output build/output
      
    - name: Login to Public ECR
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Push to ECR
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t public.ecr.aws/j7m3k0v4/aedns:$IMAGE_TAG .
        docker build -t public.ecr.aws/j7m3k0v4/aedns:latest .
        docker push --all-tags public.ecr.aws/j7m3k0v4/aedns
